### ISSUE TITLE
PVP compliance

### ISSUE THREAD

**Issue by hvr** [haskell-works/hw-prim#4]
I've noticed uploads of this package to Hackage which appear not to adhere to the [PVP](https://wiki.haskell.org/Package_versioning_policy). Complying with the PVP (which is different from SemVer) is one of the few guidelines that packages uploaded to http://hackage.haskell.org/  are expected to follow.

Specifically, I see a series of versions up to version 0.0.0.11 which appear to add new modules, add or change exported symbols, so this would at the very least require some minor version bumps (i.e. incrementing the 3rd version component, rather than the 4th), and sometimes major version bumps.

In particular, http://hdiff.luite.com/cgit/hw-prim/diff?id=0.0.0.11&id2=0.0.0.10 requires a major version bump

**Comment by newhoggy** [comment]
Thanks for the notice.  I wasn't aware of the versioning scheme.  I'll be more careful in future.
