### ISSUE TITLE
[Question] Why does Data.Naive exist?

### ISSUE THREAD

**Issue by neongreen** [haskell-works/hw-prim#42]
Just curious! I stumbled upon the little ecosystem that you have and I wonder what was the reason for recreating certain things (e.g. `HaskellWorks.Data.Naive`, which seems to be just `Identity`).

**Comment by newhoggy** [comment]
It's for providing reference implementation behaviour to test against.

For example, if I have some typeclass functions that work on `Word64`, I want those functions to be fast, which sometimes means the implementation is non-obvious.  The same library could provide a slow, but straightfoward implementation `Naive Word64`, then I can do a property test to assert the two behave the same.

**Comment by neongreen** [comment]
Aha, makes sense. Thanks!
